### ISSUE TITLE
Color codes don't work in chat messages

### ISSUE THREAD

**Issue by mathiascode** [NiLSPACE/Chatter#1]
After enabling the plugin, color codes no longer work in chat messages.

**Comment by NiLSPACE** [comment]
That's odd, could you post your config file?

**Comment by mathiascode** [comment]
Sure!

``` lua
Prefix         = "@4[OP] @r{PLAYERNAME}@f: {MESSAGE}",
UsePlayerColor = true,
UseRankColor   = false,
ChatPerWorld   = false,
ColorSymbol    = "@",

PersonalPrefixes =
{
        -- ["missingchar"] = "@9[THE REAL FOUNDER/OWNER :P] @9{PLAYERNAME}@f: {MESSAGE}",
},

RankPrefixes =
{
        ["Default"] = "@4[OP] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Founder"] = "@8[FOUNDER] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Owner"] = "@3[OWNER] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Admin"] = "@6[ADMIN] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Moderator"] = "@2[MODERATOR] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Hacker"] = "@0[HACKER] @r{PLAYERNAME}@f: {MESSAGE}",
        ["VIP"] = "@5[VIP] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Helper"] = "@2[HELPER] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Builder"] = "@6[BUILDER] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Head_Admin"] = "@6[HEAD ADMIN] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Head_Moderator"] = "@2[HEAD MODERATOR] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Head_Builder"] = "@6[HEAD BUILDER] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Trial_Moderator"] = "@2[TRIAL MODERATOR] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Manager"] = "@8[MANAGER] @r{PLAYERNAME}@f: {MESSAGE}",
        ["Head_Manager"] = "@8[HEAD MANAGER] @r{PLAYERNAME}@f: {MESSAGE}",

},
```

**Comment by NiLSPACE** [comment]
Could you try now? The reason it didn't work was because it wasn't implemented yet ;)

You can use chatcolors in chat if the player has the `chatter.usecolors` permission and if it is enabled. You can enable it by adding `AllowChatColor = true,` to the config.

Then you can use the color symbol that you already have configured.

**Comment by NiLSPACE** [comment]
@mathias-github did it work?

**Comment by mathiascode** [comment]
Thanks! It works without any problems ;)

**Comment by NiLSPACE** [comment]
I just realized that you *should* be able to replace all those RankPrefixes with this:
```lua
(function()
   local res = {}
   for Idx, Value in cRankManager:GetAllRanks() do
      res[Idx] = "@8[" .. Value:gsub("_", " "):upper() .. "] @r{PLAYERNAME}@f: {MESSAGE}"
   end
   return unpack(res)
end)()
```
(though if you want to try it you might want to backup your config first :P)

The advantage of this is that if you rename/remove/add a rank it automatically reloads properly.

**Comment by NiLSPACE** [comment]
< offtopic >
@mathias-github
I just realized that you could replace all those RankPrefixes with:

``` lua
RankPrefixes = (function()
   local Ranks = cRankManager:GetAllRanks()
   local res = {}
   for Idx, RankName in ipairs(Ranks) do
      res[RankName] = "[" .. RankName:gsub("_", " "):upper() .. "] @r{PLAYERNAME}@f: {MESSAGE}"
   end
   return res
end)(),
```

And then setting `UseRankColor` to true + giving each rank their color in the core's rank manager.
The advantage would be that when you remove/rename/add a rank it would automatically be supported.

**if** you want to try this you might want to make a backup of your config file first though :P
< /offtopic >

**Comment by mathiascode** [comment]
This won't work for me, as I use the color set in the rank manager for usernames, and a darker color for ranks.

**Comment by NiLSPACE** [comment]
Oh, I didn't notice that ;)
